[include]
files = [
    "bars/three-pill-bar.toml"
]

[shell]
polkit_agent = true
settings_window_translucent = true
time_format = "%l:%M %p"
date_format = "%e %b %Y"
font_family = "sans-serif"

[shell.panel]
transparency_mode = "glass"
open_near_click_control_center = true
control_center_placement = "floating"
wallpaper_placement = "floating"
session_placement = "floating"
floating_offset = 6

[shell.launcher]
categories = false
auto_paste = "off"

[shell.launcher.dmenu.entry.display]
command = "printf 'Mirror\nExtend\nMain monitor only'"
label = "Display"
prefix = "display"
glyph = "device-desktop"
exec = "hyprctl eval 'SetDefaultMonitorMode(\"{selection}\")' && hyprctl reload"

[shell.greeter_sync]
auto_sync = true

[shell.mpris]
blacklist = ["Mozilla Zen"]

[shell.screenshot]
save_to_file = false
confirm_region = true

[keybinds]
up = ["up", "ctrl+p"]
down = ["down", "ctrl+n"]

[control_center]
sidebar_section = "none"
hidden_tabs = [
    "media",
    "power",
    "audio",
    "network",
    "bluetooth",
    "notifications",
    "calendar",
]
shortcuts = [
    { type = "nightlight" },
    { type = "8bury/lid-guard:lid-guard-toggle" },
]

[notification]
background_opacity = 0.65
offset_y = 20

[notification.filter.lid-guard]
match_content = "^Lid Guard (enabled|disabled)$"
show_toast = false
save_history = false
play_sound = false

[location]
auto_locate = true

[nightlight]
enabled = true
temperature_night = 5000

[osd.kinds]
keyboard_layout = false
media = false

[theme]
source = "community"
community_palette = "Catppuccin Mocha Mauve-Lavender"

[plugins]
enabled = [
    "8bury/lid-guard",
]
