-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL P2217H 668VC75V76VU",
  mode = "1920x1080@60.00",
  position = "1600x-80",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Lenovo Group Limited 0x9059",
  mode = "1920x1080@120.00",
  position = "0x469",
  scale = 1.2,
  vrr = 0,
  bitdepth = 10,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL P2217H 668VC75V76VU", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Dell Inc. DELL P2217H 668VC75V76VU" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Lenovo Group Limited 0x9059", default = true, persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:Dell Inc. DELL P2217H 668VC75V76VU" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Dell Inc. DELL P2217H 668VC75V76VU" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Dell Inc. DELL P2217H 668VC75V76VU" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Dell Inc. DELL P2217H 668VC75V76VU" })
