-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Lenovo Group Limited 0x9059",
  mode = "1920x1080@120.00",
  position = "0x469",
  scale = 1.2,
  vrr = 0,
  bitdepth = 10,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "3", monitor = "desc:Lenovo Group Limited 0x9059", default = true, persistent = true })
