#: Fonts 

font_family      JetBrainsMono NF
bold_font        JetBrainsMono NF ExtraBold 
italic_font      JetBrainsMono NF Italic  
bold_italic_font JetBrainsMono NF ExtraBold Italic

font_size 13.0

#: Cursor customization

cursor_blink_interval 0
# cursor_trail 1
# cursor_trail_decay 0.01 0.15

#: Scrollback

scrollback_lines 10000
# scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollbar always

#: Mouse

show_hyperlink_targets yes
strip_trailing_spaces smart

#: Terminal bell

enable_audio_bell no
bell_on_tab ""

#: Window layout

placement_strategy top

# Uncomment this to get rid of weird shadows in WSLg
# hide_window_decorations yes

#: Tab bar

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 1
active_tab_font_style bold

#: Advanced

allow_remote_control socket-only
listen_on unix:/tmp/kitty
shell_integration enabled

#: Keyboard shortcuts

clear_all_shortcuts yes

map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+s paste_from_selection

map kitty_mod+k remote_control scroll-window 4-
map kitty_mod+j remote_control scroll-window 4

map kitty_mod+u scroll_page_up
map kitty_mod+d scroll_page_down

map kitty_mod+g scroll_home
map kitty_mod+alt+g scroll_end

map kitty_mod+z scroll_to_prompt -1
map kitty_mod+x scroll_to_prompt 1

map ctrl+backspace send_key ctrl+w
map kitty_mod+backspace send_key ctrl+backspace

# Tab management
map kitty_mod+l next_tab
map kitty_mod+h previous_tab

map kitty_mod+t new_tab_with_cwd
map kitty_mod+n new_tab
map kitty_mod+q close_tab

map kitty_mod+. move_tab_forward
map kitty_mod+, move_tab_backward

map kitty_mod+alt+t set_tab_title
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9

# Font sizes
map kitty_mod+equal  change_font_size all +2.0
map kitty_mod+plus   change_font_size all +2.0
map kitty_mod+kp_add change_font_size all +2.0

map kitty_mod+minus       change_font_size all -2.0
map kitty_mod+kp_subtract change_font_size all -2.0

map kitty_mod+0 change_font_size all 0

map kitty_mod+e open_url_with_hints

# Miscellaneous
map f11 toggle_fullscreen

map kitty_mod+p    kitten unicode_input

map kitty_mod+r load_config_file
map kitty_mod+f5 debug_config


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

background_opacity 0.85
